// Datos reales de Huancavelica
const sampleData = {
    categories: [
        { name: 'Atractivos', icon: 'map-pin' },
        { name: 'Restaurantes', icon: 'utensils' },
        { name: 'Hoteles', icon: 'hotel' },
        { name: 'Agencias', icon: 'building-2' },
        { name: 'Artesanía', icon: 'shopping-bag' },
        { name: 'Festividades', icon: 'calendar' },
    ],
    items: {
        'Atractivos': [
            { 
                id: 1, 
                name: 'Plaza de Armas de Huancavelica', 
                description: 'El corazón de la ciudad, rodeada de impresionantes edificios coloniales como la Catedral de San Antonio y el Palacio Municipal. Un lugar lleno de historia y cultura donde convergen tradiciones andinas y españolas.', 
                image: 'https://www.netravel.pe/wp-content/uploads/2018/10/Plaza-de-armas-de-Huancavelica.jpg', 
                rating: 4.7, 
                distance: 'Centro',
                coordinates: { lat: -12.7866, lng: -74.9754 },
                phone: '+51 967 123 456',
                hours: 'Todo el día',
                website: 'https://munihuancavelica.gob.pe',
                address: 'Plaza de Armas, Huancavelica',
                type: 'Plaza Principal',
                price: 'Gratuito',
                bestTime: 'Todo el año',
                tips: 'Visitar los domingos para ver la ceremonia de izamiento de bandera'
            },
            { 
                id: 2, 
                name: 'Iglesia San Francisco', 
                description: 'Joy arquitectónica del siglo XVI, famosa por su impresionante fachada barroca y retablos tallados en madera. Considerada una de las iglesias más bellas de la región andina.', 
                image: 'https://dcn5i49zim2n2.cloudfront.net/datahub/turismo/1145/471474.jpg', 
                rating: 4.8, 
                distance: '0.3 km',
                coordinates: { lat: -12.7852, lng: -74.9736 },
                phone: '+51 967 123 457',
                hours: '8:00 AM - 6:00 PM',
                website: '',
                address: 'Jr. San Francisco 123',
                type: 'Iglesia Colonial',
                price: 'Gratuito',
                bestTime: 'Mañanas',
                tips: 'Asistir a misa para experimentar la tradición religiosa local'
            },
            { 
                id: 3, 
                name: 'Complejo Arqueológico de Uchkus Inkañan', 
                description: 'Centro ceremonial inca situado a 3,800 msnm, con observatorios astronómicos, andenes y recintos ceremoniales. Ofrece vistas panorámicas espectaculares de los Andes.', 
                image: 'https://www.iperu.org/wp-content/uploads/2016/01/complejo-arqueologico-de-uchkus-inkanan.jpg', 
                rating: 4.9, 
                distance: '12 km',
                coordinates: { lat: -12.8500, lng: -74.9000 },
                phone: '+51 967 123 458',
                hours: '7:00 AM - 4:00 PM',
                website: '',
                address: 'Distrito de Yauli',
                type: 'Sitio Arqueológico',
                price: 'S/ 5.00',
                bestTime: 'Abril - Octubre',
                tips: 'Llevar ropa abrigadora y agua'
            },
            { 
                id: 4, 
                name: 'Bosque de Piedra de Sachapite', 
                description: 'Formaciones rocosas erosionadas que crean un paisaje surrealista similar a una ciudad de piedra. Ideal para fotografía y caminatas.', 
                image: 'https://antipode-peru.com/Que-Voir/bosque-de-piedras-de-sachapite--v1-1200-800.jpeg', 
                rating: 4.6, 
                distance: '8 km',
                coordinates: { lat: -12.8000, lng: -74.9500 },
                phone: '',
                hours: 'Todo el día',
                website: '',
                address: 'Distrito de Ascensión',
                type: 'Atractivo Natural',
                price: 'Gratuito',
                bestTime: 'Temporada seca',
                tips: 'Ideal para amanecer y atardecer'
            },
            { 
                id: 5, 
                name: 'Baños Termales de San Cristóbal', 
                description: 'Aguas termales medicinales ricas en minerales, conocidas por sus propiedades terapéuticas. Temperaturas entre 35°C y 40°C.', 
                image: 'https://antipode-peru.com/Que-Voir/bains-thermaux-de-san-cristobal-v1-1200-800.jpeg', 
                rating: 4.5, 
                distance: '5 km',
                coordinates: { lat: -12.7700, lng: -74.9800 },
                phone: '+51 967 123 459',
                hours: '6:00 AM - 8:00 PM',
                website: '',
                address: 'Barrio de San Cristóbal',
                type: 'Termas Medicinales',
                price: 'S/ 05.00',
                bestTime: 'Todo el año',
                tips: 'Llevar traje de baño y toalla'
            }
        ],
        'Restaurantes': [
            { 
                id: 6, 
                name: 'El Fogón Huancavelicano', 
                description: 'Restaurante familiar especializado en gastronomía local. Destacan la pachamanca, el mondongo y la trucha frita. Ambiente cálido y servicio tradicional.', 
                image: 'https://pluma-informativa507.com/wp-content/uploads/2025/01/EL-FOGON-1-1024x1325.jpg', 
                rating: 4.6, 
                distance: '0.2 km',
                coordinates: { lat: -12.7858, lng: -74.9742 },
                phone: '+51 967 123 460',
                hours: '7:00 AM - 10:00 PM',
                website: '',
                address: 'Jr. Lima 234',
                type: 'Comida Tradicional',
                price: 'S/ 15-30',
                specialities: ['Pachamanca', 'Trucha Frita', 'Caldo de Cabeza']
            },
            { 
                id: 7, 
                name: 'La Casona del Sabor', 
                description: 'Elegante restaurante ubicado en una casona colonial restaurada. Ofrece fusión de comida andina y contemporánea con ingredientes locales.', 
                image: 'https://tse4.mm.bing.net/th/id/OIP.qmek5bWhivmIIKwdQ1KcHgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3', 
                rating: 4.8, 
                distance: '0.4 km',
                coordinates: { lat: -12.7872, lng: -74.9768 },
                phone: '+51 967 123 461',
                hours: '12:00 PM - 11:00 PM',
                website: 'lacasonadelsabor.com',
                address: 'Jr. Carabaya 567',
                type: 'Gastronómico',
                price: 'S/ 25-50',
                specialities: ['Cuy Chactado', 'Rocoto Relleno', 'Causa Limeña']
            },
            { 
                id: 8, 
                name: 'Picantería Doña Margarita', 
                description: 'Auténtica picantería local con 40 años de tradición. Ambiente rústico y platos preparados con recetas ancestrales.', 
                image: 'https://tse4.mm.bing.net/th/id/OIP.0t0zcAi97qZCsK9Fq1pxzgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3', 
                rating: 4.7, 
                distance: '0.8 km',
                coordinates: { lat: -12.7890, lng: -74.9801 },
                phone: '+51 967 123 462',
                hours: '8:00 AM - 6:00 PM',
                website: '',
                address: 'Av. Virrey Toledo 789',
                type: 'Picantería Tradicional',
                price: 'S/ 12-25',
                specialities: ['Picante de Cuy', 'Chicharrón', 'Tamales']
            }
        ],
        'Hoteles': [
            { 
                id: 9, 
                name: 'Hotel Presidente Huancavelica', 
                description: 'Hotel 4 estrellas con todas las comodidades modernas. Ubicado frente a la Plaza de Armas, ofrece vistas panorámicas y servicio de primera.', 
                image: 'https://s3.us-east-1.amazonaws.com/ca-webprod/Ambientes/fachada-hotel-asociado-casa-andina-hotel-presidente-huancavelica-1761136635.jpg', 
                rating: 4.5, 
                distance: '0.1 km',
                coordinates: { lat: -12.7861, lng: -74.9751 },
                phone: '+51 967 123 463',
                hours: 'Recepción 24 horas',
                website: 'hotelpresidentehuancavelica.com',
                address: 'Plaza de Armas 123',
                type: 'Hotel 4 Estrellas',
                price: 'S/ 120-250',
                amenities: ['WiFi', 'Restaurante', 'Spa', 'Estacionamiento']
            },
            { 
                id: 10, 
                name: 'Hostal De Los Andes', 
                description: 'Acogedor hostal familiar con ambiente cálido y atención personalizada. Ideal para mochileros y viajeros que buscan autenticidad.', 
                image: 'https://tse1.mm.bing.net/th/id/OIP.GJdieksU8DJxLyGFIPr8wAHaHZ?rs=1&pid=ImgDetMain&o=7&rm=3', 
                rating: 4.2, 
                distance: '0.3 km',
                coordinates: { lat: -12.7845, lng: -74.9762 },
                phone: '+51 967 123 464',
                hours: 'Recepción 24 horas',
                website: 'hostallosandes.com',
                address: 'Jr. Cusco 456',
                type: 'Hostal Económico',
                price: 'S/ 40-80',
                amenities: ['WiFi', 'Cocina Compartida', 'Terraza', 'Lavandería']
            },
            { 
                id: 11, 
                name: 'Huaytara Loge', 
                description: 'Alojamiento ecológico situado en las afueras de la ciudad. Ofrece conexión con la naturaleza y actividades de turismo vivencial.', 
                image: 'https://tse3.mm.bing.net/th/id/OIP.X7mzbeR2YxjkZD4ORik_HAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3', 
                rating: 4.9, 
                distance: '3 km',
                coordinates: { lat: -12.7893, lng: -74.9785 },
                phone: '+51 967 123 465',
                hours: 'Recepción 24 horas',
                website: 'ecolodgesantuario.com',
                address: 'Carretera a Lircay Km 3',
                type: 'Eco Lodge',
                price: 'S/ 80-150',
                amenities: ['WiFi', 'Restaurante Orgánico', 'Tours', 'Jardín']
            }
        ],
        'Agencias': [
            
            { 
                id: 13, 
                name: 'Huancavelica Travel', 
                description: 'Operadora turística con 15 años de experiencia. Paquetes todo incluido y servicios personalizados para grupos e individuos.', 
                image: 'https://blog.viajesmachupicchu.travel/wp-content/uploads/2023/09/huancavelica-9.jpg', 
                rating: 4.6, 
                distance: '0.5 km',
                coordinates: { lat: -12.7870, lng: -74.9770 },
                phone: '+51 967 123 467',
                hours: '8:00 AM - 6:00 PM',
                website: 'huancavelicatravel.com',
                address: 'Av. Arenales 678',
                type: 'Operadora Turística',
                services: ['Paquetes Turísticos', 'Transporte', 'Guías Especializados', 'Reservas Hoteleras']
            }
        ],
        'Artesanía': [
            { 
                id: 14, 
                name: 'Mercado Artesanal Santa Ana', 
                description: 'Mercado tradicional donde artesanos locales exhiben y venden sus productos. Textiles, cerámica, joyería y productos locales.', 
                image: 'https://images.unsplash.com/photo-1585007600263-71228e40c8d1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 
                rating: 4.4, 
                distance: '0.6 km',
                coordinates: { lat: -12.7880, lng: -74.9790 },
                phone: '+51 967 123 468',
                hours: '7:00 AM - 5:00 PM',
                website: '',
                address: 'Barrio de Santa Ana',
                type: 'Mercado Artesanal',
                products: ['Textiles', 'Cerámica', 'Joyería', 'Productos Locales']
            },
            { 
                id: 15, 
                name: 'Taller de Tejidos Andinos', 
                description: 'Taller familiar donde se mantienen vivas las técnicas ancestrales de tejido. Visitas guiadas y demostraciones en vivo.', 
                image: 'https://portal.andina.pe/EDPfotografia/Thumbnail/2013/12/20/000228432W.jpg', 
                rating: 4.7, 
                distance: '1.2 km',
                coordinates: { lat: -12.7900, lng: -74.9820 },
                phone: '+51 967 123 469',
                hours: '9:00 AM - 4:00 PM',
                website: '',
                address: 'Comunidad de Acoria',
                type: 'Taller Artesanal',
                products: ['Ponchos', 'Chullos', 'Alforjas', 'Tapices']
            }
        ],
        'Festividades': [
            { 
                id: 16, 
                name: 'Festividad de los Reyes Magos', 
                description: 'Celebración religiosa y cultural que se realiza cada 6 de enero. Procesiones, danzas tradicionales y ferias gastronómicas.', 
                image: 'https://i.pinimg.com/736x/3d/af/2b/3daf2bf4bf81acd2c64c198e05f27012.jpg', 
                rating: 4.9, 
                distance: 'Centro',
                coordinates: { lat: -12.7866, lng: -74.9754 },
                phone: '',
                hours: 'Todo el día',
                website: '',
                address: 'Plaza de Armas y calles aledañas',
                type: 'Festividad Religiosa',
                date: '6 de Enero',
                activities: ['Procesión', 'Danzas', 'Feria Gastronómica', 'Fuegos Artificiales']
            },
            { 
                id: 17, 
                name: 'Carnaval Huancavelicano', 
                description: 'Fiesta tradicional donde se celebra la fertilidad de la tierra. Juegos con agua, yunzas y competencias de danzas folklóricas.', 
                image: 'https://th.bing.com/th/id/R.53f01df4873246ac87d4e8a3ae2eb3b2?rik=AifCodXRn%2br%2fnw&pid=ImgRaw&r=0', 
                rating: 4.8, 
                distance: 'Centro',
                coordinates: { lat: -12.7866, lng: -74.9754 },
                phone: '',
                hours: 'Todo el día',
                website: '',
                address: 'Toda la ciudad',
                type: 'Fiesta Popular',
                date: 'Febrero/Marzo',
                activities: ['Cortamonte', 'Juegos con Agua', 'Competencia de Danzas', 'Ferias']
            }
        ]
    },
    promotions: [
        {
            id: 1,
            title: 'Paquete Cultural Completo',
            description: 'Tour por los principales atractivos históricos con guía especializado',
            discount: '25%',
            price: 'S/ 150',
            originalPrice: 'S/ 200',
            validUntil: '2025-12-31',
            agency: 'Andean Explorers Tours'
        },
        {
            id: 2,
            title: 'Noche de Hotel + Desayuno',
            description: 'Alojamiento en Hotel Presidente con desayuno buffet incluido',
            discount: '30%',
            price: 'S/ 84',
            originalPrice: 'S/ 120',
            validUntil: '2025-11-30',
            agency: 'Hotel Presidente'
        },
        {
            id: 3,
            title: 'Experiencia Gastronómica',
            description: 'Menú degustación en La Casona del Sabor con bebidas incluidas',
            discount: '20%',
            price: 'S/ 80',
            originalPrice: 'S/ 100',
            validUntil: '2025-10-31',
            agency: 'La Casona del Sabor'
        }
    ],
    reservations: [],
    favorites: []
};